export const ADDED_RESTAURANT_TO_FAVOURITE = "add restaurant to favourite";
export const REMOVED_RESTAURANT_FROM_FAVOURITE = "remove restaurant from favourite";
export const SORTED_RESTAURANTS = "sort restaurants";
export const FILTERED_RESTAURANTS = "filter restaurants";
export const ADDED_DEFAULT_RESTAURANTS = "added default restaurant";
export const LOADED_FAVOURITE_RESTAURANTS = "loaded favourite restaurants";
export const RESTORED_RESTAURANTS_TO_RENDER = "updated restaurants to render";
export const RESTORED_FAVOURITE_RESTAURANTS_TO_RENDER = "updated favourite restaurants to render";
export const SET_SELECTED_SORT_PROPERTIES = "set selected sort properties";
